// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tenant

import (
	"backend/api/tenant"
)

type ControllerV1 struct{}

func NewV1() tenant.ITenantV1 {
	return &ControllerV1{}
}
