// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package ws

import (
	"backend/api/ws"
)

type ControllerV1 struct{}

func NewV1() ws.IWsV1 {
	return &ControllerV1{}
}
