// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_permission

import (
	"context"

	"backend/api/sys_permission/v1"
	"backend/internal/model"
	"backend/internal/service"
)

func (c *ControllerV1) GetPermissionsByUser(ctx context.Context, req *v1.GetPermissionsByUserReq) (res *v1.GetPermissionsByUserRes, err error) {
	if req == nil {
		req = &v1.GetPermissionsByUserReq{}
	}
	out, err := service.SysRole().GetPermissionsByUser(ctx, model.UserPermissionsIn{UserID: req.UserID})
	if err != nil {
		return nil, err
	}
	res = &v1.GetPermissionsByUserRes{UserPermissionsOut: out}
	return
}

func (c *ControllerV1) GetPermissionList(ctx context.Context, req *v1.GetPermissionListReq) (res *v1.GetPermissionListRes, err error) {
	if req == nil {
		req = &v1.GetPermissionListReq{}
	}
	out, err := service.SysPermission().GetPermissionList(ctx, model.SysPermissionListIn{
		Page:     req.Page,
		PageSize: req.PageSize,
		Name:     req.Name,
		Status:   req.Status,
	})
	if err != nil {
		return nil, err
	}
	res = &v1.GetPermissionListRes{
		Items: out.Items,
		Total: out.Total,
	}
	return
}

func (c *ControllerV1) GetPermissionTree(ctx context.Context, req *v1.GetPermissionTreeReq) (res *v1.GetPermissionTreeRes, err error) {
	if req == nil {
		req = &v1.GetPermissionTreeReq{}
	}
	list, err := service.SysPermission().GetPermissionTree(ctx)
	if err != nil {
		return nil, err
	}
	res = &v1.GetPermissionTreeRes{List: list}
	return
}
