// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_message

import (
	"backend/api/sys_message"
)

type ControllerV1 struct{}

func NewV1() sys_message.ISysMessageV1 {
	return &ControllerV1{}
}
