// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"

	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// sysDictTypeDao is the data access object for the table sys_dict_type.
// You can define custom methods on it to extend its functionality as needed.
type sysDictTypeDao struct {
	*internal.SysDictTypeDao
}

var (
	// SysDictType is a globally accessible object for table sys_dict_type operations.
	SysDictType = sysDictTypeDao{internal.NewSysDictTypeDao()}
)

// Add your custom methods and functionality below.

// Ctx returns tenant-scoped model by default.
func (dao sysDictTypeDao) Ctx(ctx context.Context) *gdb.Model {
	return withTenant(ctx, dao.SysDictTypeDao.Ctx(ctx))
}

// CtxNoTenant returns model without tenant scoping (use carefully).
func (dao sysDictTypeDao) CtxNoTenant(ctx context.Context) *gdb.Model {
	return dao.SysDictTypeDao.Ctx(ctx)
}
