// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"

	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// sysRoleDao is the data access object for the table sys_role.
// You can define custom methods on it to extend its functionality as needed.
type sysRoleDao struct {
	*internal.SysRoleDao
}

var (
	// SysRole is a globally accessible object for table sys_role operations.
	SysRole = sysRoleDao{internal.NewSysRoleDao()}
)

// Add your custom methods and functionality below.

// Ctx returns tenant-scoped model by default.
func (dao sysRoleDao) Ctx(ctx context.Context) *gdb.Model {
	return withTenant(ctx, dao.SysRoleDao.Ctx(ctx))
}

// CtxNoTenant returns model without tenant scoping (use carefully).
func (dao sysRoleDao) CtxNoTenant(ctx context.Context) *gdb.Model {
	return dao.SysRoleDao.Ctx(ctx)
}
