// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"

	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// sysDeptDao is the data access object for the table sys_dept.
// You can define custom methods on it to extend its functionality as needed.
type sysDeptDao struct {
	*internal.SysDeptDao
}

var (
	// SysDept is a globally accessible object for table sys_dept operations.
	SysDept = sysDeptDao{internal.NewSysDeptDao()}
)

// Add your custom methods and functionality below.

// Ctx returns tenant-scoped model by default.
func (dao sysDeptDao) Ctx(ctx context.Context) *gdb.Model {
	return withTenant(ctx, dao.SysDeptDao.Ctx(ctx))
}

// CtxNoTenant returns model without tenant scoping (use carefully).
func (dao sysDeptDao) CtxNoTenant(ctx context.Context) *gdb.Model {
	return dao.SysDeptDao.Ctx(ctx)
}
