// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// sysMessageDao is the data access object for the table sys_message.
// You can define custom methods on it to extend its functionality as needed.
type sysMessageDao struct {
	*internal.SysMessageDao
}

var (
	// SysMessage is a globally accessible object for table sys_message operations.
	SysMessage = sysMessageDao{internal.NewSysMessageDao()}
)

// Add your custom methods and functionality below.
