// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"

	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// sysDictDataDao is the data access object for the table sys_dict_data.
// You can define custom methods on it to extend its functionality as needed.
type sysDictDataDao struct {
	*internal.SysDictDataDao
}

var (
	// SysDictData is a globally accessible object for table sys_dict_data operations.
	SysDictData = sysDictDataDao{internal.NewSysDictDataDao()}
)

// Add your custom methods and functionality below.

// Ctx returns tenant-scoped model by default.
func (dao sysDictDataDao) Ctx(ctx context.Context) *gdb.Model {
	return withTenant(ctx, dao.SysDictDataDao.Ctx(ctx))
}

// CtxNoTenant returns model without tenant scoping (use carefully).
func (dao sysDictDataDao) CtxNoTenant(ctx context.Context) *gdb.Model {
	return dao.SysDictDataDao.Ctx(ctx)
}
