// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"

	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// sysMenuDao is the data access object for the table sys_menu.
// You can define custom methods on it to extend its functionality as needed.
type sysMenuDao struct {
	*internal.SysMenuDao
}

var (
	// SysMenu is a globally accessible object for table sys_menu operations.
	SysMenu = sysMenuDao{internal.NewSysMenuDao()}
)

// Add your custom methods and functionality below.

// Ctx returns tenant-scoped model by default.
func (dao sysMenuDao) Ctx(ctx context.Context) *gdb.Model {
	return withTenant(ctx, dao.SysMenuDao.Ctx(ctx))
}

// CtxNoTenant returns model without tenant scoping (use carefully).
func (dao sysMenuDao) CtxNoTenant(ctx context.Context) *gdb.Model {
	return dao.SysMenuDao.Ctx(ctx)
}
