// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"

	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// sysUserDao is the data access object for the table sys_user.
// You can define custom methods on it to extend its functionality as needed.
type sysUserDao struct {
	*internal.SysUserDao
}

var (
	// SysUser is a globally accessible object for table sys_user operations.
	SysUser = sysUserDao{internal.NewSysUserDao()}
)

// Add your custom methods and functionality below.

// Ctx returns tenant-scoped model by default.
func (dao sysUserDao) Ctx(ctx context.Context) *gdb.Model {
	return withTenant(ctx, dao.SysUserDao.Ctx(ctx))
}

// CtxNoTenant returns model without tenant scoping (use carefully).
func (dao sysUserDao) CtxNoTenant(ctx context.Context) *gdb.Model {
	return dao.SysUserDao.Ctx(ctx)
}
