// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// sysTenantDao is the data access object for the table sys_tenant.
// You can define custom methods on it to extend its functionality as needed.
type sysTenantDao struct {
	*internal.SysTenantDao
}

var (
	// SysTenant is a globally accessible object for table sys_tenant operations.
	SysTenant = sysTenantDao{internal.NewSysTenantDao()}
)

// Add your custom methods and functionality below.
