// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"

	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// sysPermissionDao is the data access object for the table sys_permission.
// You can define custom methods on it to extend its functionality as needed.
type sysPermissionDao struct {
	*internal.SysPermissionDao
}

var (
	// SysPermission is a globally accessible object for table sys_permission operations.
	SysPermission = sysPermissionDao{internal.NewSysPermissionDao()}
)

// Add your custom methods and functionality below.

// Ctx returns tenant-scoped model by default.
func (dao sysPermissionDao) Ctx(ctx context.Context) *gdb.Model {
	return withTenant(ctx, dao.SysPermissionDao.Ctx(ctx))
}

// CtxNoTenant returns model without tenant scoping (use carefully).
func (dao sysPermissionDao) CtxNoTenant(ctx context.Context) *gdb.Model {
	return dao.SysPermissionDao.Ctx(ctx)
}
