// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"

	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// sysRolePermissionDao is the data access object for the table sys_role_permission.
// You can define custom methods on it to extend its functionality as needed.
type sysRolePermissionDao struct {
	*internal.SysRolePermissionDao
}

var (
	// SysRolePermission is a globally accessible object for table sys_role_permission operations.
	SysRolePermission = sysRolePermissionDao{internal.NewSysRolePermissionDao()}
)

// Add your custom methods and functionality below.

// Ctx returns model WITHOUT tenant scoping (this table没有 tenant_id 列).
func (dao sysRolePermissionDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.SysRolePermissionDao.Ctx(ctx)
}
