// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// sysRolePermissionDao is the data access object for the table sys_role_permission.
// You can define custom methods on it to extend its functionality as needed.
type sysRolePermissionDao struct {
	*internal.SysRolePermissionDao
}

var (
	// SysRolePermission is a globally accessible object for table sys_role_permission operations.
	SysRolePermission = sysRolePermissionDao{internal.NewSysRolePermissionDao()}
)

// Add your custom methods and functionality below.
