// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"

	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// sysUserRoleDao is the data access object for the table sys_user_role.
// You can define custom methods on it to extend its functionality as needed.
type sysUserRoleDao struct {
	*internal.SysUserRoleDao
}

var (
	// SysUserRole is a globally accessible object for table sys_user_role operations.
	SysUserRole = sysUserRoleDao{internal.NewSysUserRoleDao()}
)

// Add your custom methods and functionality below.

// Ctx returns tenant-scoped model by default.
func (dao sysUserRoleDao) Ctx(ctx context.Context) *gdb.Model {
	return withTenant(ctx, dao.SysUserRoleDao.Ctx(ctx))
}

// CtxNoTenant returns model without tenant scoping (use carefully).
func (dao sysUserRoleDao) CtxNoTenant(ctx context.Context) *gdb.Model {
	return dao.SysUserRoleDao.Ctx(ctx)
}
