// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// sysMessageReadDao is the data access object for the table sys_message_read.
// You can define custom methods on it to extend its functionality as needed.
type sysMessageReadDao struct {
	*internal.SysMessageReadDao
}

var (
	// SysMessageRead is a globally accessible object for table sys_message_read operations.
	SysMessageRead = sysMessageReadDao{internal.NewSysMessageReadDao()}
)

// Add your custom methods and functionality below.
